### PR TITLE
async/await using tokio

### PR DESCRIPTION
**Pull request by icewind1991**
This builds on top of the work from #15 porting it to `std::future` and streams.

### CODE REVIEW

**Comment by icewind1991** [comment]
ping @dylanmckay

**Comment by dylanmckay** [comment]
Nice work!! Thanks for the pull request @icewind1991.

I'll push up a new major version now.

**Comment by dylanmckay** [comment]
There seems to be something strange

I get this when I try and release it locally

```
error[E0433]: failed to resolve: could not find `main` in `tokio`
 --> examples/chromecast_discovery.rs:7:10
  |
7 | #[tokio::main]
  |          ^^^^ could not find `main` in `tokio`

error[E0277]: `main` has invalid return type `impl std::future::Future`
 --> examples/chromecast_discovery.rs:8:20
  |
8 | async fn main() -> Result<(), Error> {
  |                    ^^^^^^^^^^^^^^^^^ `main` can only return types that implement `std::process::Termination`
  |
  = help: consider using `()`, or a `Result`
```

Even when the test suite passed last month on Travis.

Here's the details of the test that ran and passed on Travis last month.

```
$ rustc --version
rustc 1.39.0 (4560ea788 2019-11-04)
$ rustup --version
rustup 1.20.2 (13979c968 2019-10-16)
$ cargo --version
cargo 1.39.0 (1c6ec66d5 2019-09-30)
```

Here's the details of the test that ran and failed on Travis but failed when ran today

```
$ rustc --version
rustc 1.40.0 (73528e339 2019-12-16)
$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
$ cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)
```

It seems that this code works on rustc 1.39 but not 1.40 - weird

**Comment by j-keck** [comment]
I tested the master branch on: 4c40ffe893788dafa16126dd27dd5c11f338626e to detect Sonoff Devices  in my network.

The only change i have is a different service name:
```
~/prj/github/mdns⟩ git diff -U1
diff --git a/examples/chromecast_discovery.rs b/examples/chromecast_discovery.rs
index 0b79e68..ef3d51f 100644
--- a/examples/chromecast_discovery.rs
+++ b/examples/chromecast_discovery.rs
@@ -4,3 +4,3 @@ use std::{net::IpAddr, time::Duration};
 
-const SERVICE_NAME: &'static str = "_http._tcp.local";
+const SERVICE_NAME: &'static str = "_ewelink._tcp.local";
```

The example compiles and finds the device:
```
~/prj/github/mdns⟩ cargo run --example chromecast_discovery
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/chromecast_discovery`
found cast device at 192.168.179.24
```

I'm on rust 1.40.0:

```
~/prj/github/mdns⟩ rustc --version
rustc 1.40.0 (73528e339 2019-12-16)

~/prj/github/mdns⟩ rustup --version
rustup 1.18.3 (1970-01-01)

~/prj/github/mdns⟩ cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)
```

**Comment by icewind1991** [comment]
I have no problems running `cargo package` against master locally (rustc 1.40.0)

**Comment by icewind1991** [comment]
Ok, seems to be an change with tokio 0.2.7 requiring extra features for the macro to get imported, adding `"rt-core"` to the features in dev-dependencies seems to fix it

**Comment by dylanmckay** [comment]
@icewind1991 that fixed it, committed in #17 and pushed `1.0.0` to crates.io,

Thanks for the patch!
